/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "AstroKube/pkg/apis/astrocore/v1"
	astrocorev1 "AstroKube/pkg/client/applyconfiguration/astrocore/v1"
	scheme "AstroKube/pkg/client/clientset/versioned/scheme"
	"context"
	json "encoding/json"
	"fmt"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterListsGetter has a method to return a ClusterListInterface.
// A group's client should implement this interface.
type ClusterListsGetter interface {
	ClusterLists(namespace string) ClusterListInterface
}

// ClusterListInterface has methods to work with ClusterList resources.
type ClusterListInterface interface {
	Create(ctx context.Context, clusterList *v1.ClusterList, opts metav1.CreateOptions) (*v1.ClusterList, error)
	Update(ctx context.Context, clusterList *v1.ClusterList, opts metav1.UpdateOptions) (*v1.ClusterList, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ClusterList, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ClusterListList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterList, err error)
	Apply(ctx context.Context, clusterList *astrocorev1.ClusterListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterList, err error)
	ClusterListExpansion
}

// clusterLists implements ClusterListInterface
type clusterLists struct {
	client rest.Interface
	ns     string
}

// newClusterLists returns a ClusterLists
func newClusterLists(c *AstroV1Client, namespace string) *clusterLists {
	return &clusterLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterList, and returns the corresponding clusterList object, and an error if there is any.
func (c *clusterLists) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ClusterList, err error) {
	result = &v1.ClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterLists that match those selectors.
func (c *clusterLists) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ClusterListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterLists.
func (c *clusterLists) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterList and creates it.  Returns the server's representation of the clusterList, and an error, if there is any.
func (c *clusterLists) Create(ctx context.Context, clusterList *v1.ClusterList, opts metav1.CreateOptions) (result *v1.ClusterList, err error) {
	result = &v1.ClusterList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterList and updates it. Returns the server's representation of the clusterList, and an error, if there is any.
func (c *clusterLists) Update(ctx context.Context, clusterList *v1.ClusterList, opts metav1.UpdateOptions) (result *v1.ClusterList, err error) {
	result = &v1.ClusterList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterlists").
		Name(clusterList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterList and deletes it. Returns an error if one occurs.
func (c *clusterLists) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterlists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterLists) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterlists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterList.
func (c *clusterLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ClusterList, err error) {
	result = &v1.ClusterList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterlists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied clusterList.
func (c *clusterLists) Apply(ctx context.Context, clusterList *astrocorev1.ClusterListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ClusterList, err error) {
	if clusterList == nil {
		return nil, fmt.Errorf("clusterList provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(clusterList)
	if err != nil {
		return nil, err
	}
	name := clusterList.Name
	if name == nil {
		return nil, fmt.Errorf("clusterList.Name must be provided to Apply")
	}
	result = &v1.ClusterList{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("clusterlists").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
